### PR TITLE
Fix "unknown flow control operator" (util.zh)

### PR DESCRIPTION
**Pull request by liameno**
https://github.com/Wgmlgz/zhaba-script/issues/5

### CODE REVIEW

**Comment by liameno** [comment]
Why don't you delete dynamic objects?

**Comment by Wgmlgz** [comment]
Because, `Token` needs a valid reference to the file name string. But in other cases, the compiler relies on the operating system, that cleans up resources. I don't use smart pointers, because of runtime overhead. In future, I will probably implement a system that collects these kinds of objects and cleans everything, when compilation is complete. In this case storing filename string as a local variable, can cause bugs, when, for example, the compiler prints an error and references this string. I will also write about this in the docs, but don't have time to do this yet.

**Comment by liameno** [comment]
Do you have matrix(.org)?

**Comment by Wgmlgz** [comment]
No

**Comment by liameno** [comment]
https://github.com/Wgmlgz/zhaba-script/pull/6/commits/de6876ed9dd66eab9a53df953e55f44283d0978e ?

**Comment by Wgmlgz** [comment]
This commit looks like values from expression were put inside variables. Can you provide more info about this bug, like file that you was compiling?

**Comment by liameno** [comment]
https://github.com/Wgmlgz/zhaba-script/issues/5
```
use std

fn main
  a := Str('hello world')
  b := Str(' ')

  out a
  out find(a, b)
```

**Comment by Wgmlgz** [comment]
🤔This works fine in current main branch. Did you change other files?
```
[INFO] compiling complete in 0.142000
[INFO] C compiling complete in 2.371000
hello world
5
[INFO] run complete in 0.026000
```

**Comment by Wgmlgz** [comment]
Bytecode compilation is also fine
```
[INFO] compiling complete in 0.084000
hello world
5
[INFO] run complete in 0.010000
```

**Comment by liameno** [comment]
"unknown flow control operator" std/util.zh pos 19 line 1
stack:

parseASTblock syntax_tree_parser.cpp:436
parseImpl syntax_tree_parser.cpp:548
parseZh syntax_tree_parser.cpp:798
parseFile syntax_tree_parser.cpp:954
parseZh syntax_tree_parser.cpp:690
parseFile syntax_tree_parser.cpp:954
parseZh syntax_tree_parser.cpp:690
parseFile syntax_tree_parser.cpp:954
parseZh syntax_tree_parser.cpp:690
parseFile syntax_tree_parser.cpp:954
compileFile module_compiler.hpp:15
main zhaba.cpp:26

util.zh:

impl i8:  fn ctor: <<< 0i8

**Comment by liameno** [comment]
Perhaps we have different compilers

**Pull request closed without merging**
